version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.jetbrains.kotlin:kotlin-allopen
    versions:
    - 1.4.21-2
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin:kotlin-gradle-plugin
    versions:
    - 1.4.21-2
    - 1.4.31
    - 1.4.32
  - dependency-name: org.springframework.boot:spring-boot-gradle-plugin
    versions:
    - 2.4.3
    - 2.4.4
  - dependency-name: io.micrometer:micrometer-registry-prometheus
    versions:
    - 1.6.4
    - 1.6.5
  - dependency-name: org.springframework.cloud:spring-cloud-dependencies
    versions:
    - Hoxton.SR10
